import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '2.0.0-beta.4:0',
  releaseNotes: {
    en_US:
      'Jam 2.0.0-beta.4 on the joinmarket-ng 0.40.0 backend: Settings can sign a message with a wallet address, several UTXOs can be frozen or unfrozen at once, the sweep confirmation lists the UTXOs it will spend, sweeps and fidelity bonds spend exactly the UTXOs shown for review, a new wallet shows its creation date and starting block height, the log view follows new lines only when auto-follow is on, and uppercase Bitcoin addresses are accepted.\n\nJam 2.0 is beta software — use with caution. It installs alongside an older Jam rather than upgrading it; recover your wallet here from its seed phrase.\n\n- Reset Password asks for confirmation before it replaces your password.',
    es_ES:
      'Jam 2.0.0-beta.4 sobre el backend joinmarket-ng 0.40.0: Ajustes permite firmar un mensaje con una dirección del monedero, se pueden congelar o descongelar varios UTXO a la vez, la confirmación de un barrido enumera los UTXO que gastará, los barridos y los bonos de fidelidad gastan exactamente los UTXO mostrados para revisión, un monedero nuevo muestra su fecha de creación y su altura de bloque inicial, la vista de registros sigue las líneas nuevas solo con el seguimiento automático activado, y se aceptan direcciones de Bitcoin en mayúsculas.\n\nJam 2.0 es software beta: úsalo con precaución. Se instala junto a un Jam anterior en lugar de actualizarlo; recupera aquí tu monedero con su frase semilla.\n\n- Restablecer contraseña pide confirmación antes de sustituir tu contraseña.',
    de_DE:
      'Jam 2.0.0-beta.4 auf dem joinmarket-ng-Backend 0.40.0: In den Einstellungen lässt sich eine Nachricht mit einer Wallet-Adresse signieren, mehrere UTXOs können auf einmal eingefroren oder freigegeben werden, die Sweep-Bestätigung listet die UTXOs auf, die ausgegeben werden, Sweeps und Fidelity Bonds geben genau die zur Prüfung angezeigten UTXOs aus, eine neue Wallet zeigt ihr Erstellungsdatum und ihre Start-Blockhöhe, die Log-Ansicht folgt neuen Zeilen nur bei aktiviertem Auto-Follow, und Bitcoin-Adressen in Großbuchstaben werden akzeptiert.\n\nJam 2.0 ist Beta-Software – mit Vorsicht verwenden. Es wird neben einem älteren Jam installiert und aktualisiert dieses nicht; stelle deine Wallet hier mit ihrer Seed-Phrase wieder her.\n\n- Passwort zurücksetzen fragt nach einer Bestätigung, bevor es dein Passwort ersetzt.',
    pl_PL:
      'Jam 2.0.0-beta.4 na backendzie joinmarket-ng 0.40.0: w Ustawieniach można podpisać wiadomość adresem portfela, wiele UTXO można zamrozić lub odmrozić naraz, potwierdzenie zamiatania wymienia UTXO, które zostaną wydane, zamiatanie i obligacje wierności wydają dokładnie UTXO pokazane do przeglądu, nowy portfel pokazuje datę utworzenia i początkową wysokość bloku, widok logów śledzi nowe wiersze tylko przy włączonym automatycznym śledzeniu, a adresy Bitcoin pisane wielkimi literami są akceptowane.\n\nJam 2.0 to oprogramowanie w wersji beta – używaj ostrożnie. Instaluje się obok starszego Jam, zamiast go aktualizować; odzyskaj tutaj swój portfel z frazy seed.\n\n- Zresetuj hasło prosi o potwierdzenie, zanim zastąpi twoje hasło.',
    fr_FR:
      "Jam 2.0.0-beta.4 sur le backend joinmarket-ng 0.40.0 : les Paramètres permettent de signer un message avec une adresse du portefeuille, plusieurs UTXO peuvent être gelés ou dégelés en une fois, la confirmation d'un balayage liste les UTXO qu'il dépensera, les balayages et les obligations de fidélité dépensent exactement les UTXO présentés pour vérification, un nouveau portefeuille affiche sa date de création et sa hauteur de bloc initiale, la vue des journaux ne suit les nouvelles lignes que lorsque le suivi automatique est activé, et les adresses Bitcoin en majuscules sont acceptées.\n\nJam 2.0 est en version bêta : à utiliser avec prudence. Il s'installe à côté d'un Jam plus ancien au lieu de le mettre à jour ; restaurez ici votre portefeuille à partir de sa phrase de récupération.\n\n- Réinitialiser le mot de passe demande une confirmation avant de remplacer votre mot de passe.",
  },
  migrations: {
    up: async ({ effects }) => {},
    down: IMPOSSIBLE,
  },
})
